import json

files = {
    'en': 'lib/src/localization/arb/app_en.arb',
    'fr': 'lib/src/localization/arb/app_fr.arb',
    'ar': 'lib/src/localization/arb/app_ar.arb',
    'es': 'lib/src/localization/arb/app_es.arb'
}

data = {
    'en': {
        'deleteStr': 'Delete',
        'createConsumables': 'Create Consumables',
        'addFamilyMember': 'Add Family Member',
        'ledgerPayments': 'Ledger / Payments',
        'printDocument': 'Print Document',
        'recordPayment': 'Record Payment',
        'viewPaymentsChecks': 'View Payments & Checks',
        'productNameLabel': 'Product Name',
        'referenceLabel': 'Reference (optional)',
        'purchasePriceLabel': 'Purchase Price',
        'sellingPriceLabel': 'Selling Price',
        'tier2PriceLabel': 'Tier 2 Price (optional)',
        'tier3PriceLabel': 'Tier 3 Price (optional)',
        'packagingLabel': 'Packaging (e.g., Box, Unit)',
        'unitTypeLabel': 'Unit Type',
        'unitSizeLabel': 'Unit Size',
        'unitsPerBoxLabel': 'Units Per Box',
        'baseMinStockLabel': 'Base Min Stock',
        'magazinMinStockLabel': 'Magazin Min Stock',
        'arabicTagLabel': 'Arabic Tag',
        'frenchTagLabel': 'French Tag',
        'spanishTagLabel': 'Spanish Tag',
        'saveStr': 'Save',
        'cancelStr': 'Cancel',
        'stockLevelLabel': 'Stock Levels',
        'baseLabel': 'Base',
        'magazinLabel': 'Magazin',
        'dashboardTitle': 'Dashboard',
        'stockTitle': 'Stock',
        'salesTitle': 'Sales',
        'totalSalesLabel': 'Total Sales',
        'totalPurchasesLabel': 'Total Purchases',
        'cashInRegisterLabel': 'Cash in Register',
        'recentTransactionsLabel': 'Recent Transactions'
    },
    'fr': {
        'deleteStr': 'Supprimer',
        'createConsumables': 'Créer des consommables',
        'addFamilyMember': 'Ajouter un membre à la famille',
        'ledgerPayments': 'Registre / Paiements',
        'printDocument': 'Imprimer le document',
        'recordPayment': 'Enregistrer un paiement',
        'viewPaymentsChecks': 'Voir les paiements et chèques',
        'productNameLabel': 'Nom du produit',
        'referenceLabel': 'Référence (optionnelle)',
        'purchasePriceLabel': "Prix d'achat",
        'sellingPriceLabel': 'Prix de vente',
        'tier2PriceLabel': 'Prix Tier 2 (optionnel)',
        'tier3PriceLabel': 'Prix Tier 3 (optionnel)',
        'packagingLabel': 'Emballage (ex: Boîte, Unité)',
        'unitTypeLabel': 'Type d\'unité',
        'unitSizeLabel': 'Taille d\'unité',
        'unitsPerBoxLabel': 'Unités par boîte',
        'baseMinStockLabel': 'Stock min Base',
        'magazinMinStockLabel': 'Stock min Magasin',
        'arabicTagLabel': 'Tag en arabe',
        'frenchTagLabel': 'Tag en français',
        'spanishTagLabel': 'Tag en espagnol',
        'saveStr': 'Enregistrer',
        'cancelStr': 'Annuler',
        'stockLevelLabel': 'Niveaux de stock',
        'baseLabel': 'Base',
        'magazinLabel': 'Magasin',
        'dashboardTitle': 'Tableau de bord',
        'stockTitle': 'Stock',
        'salesTitle': 'Ventes',
        'totalSalesLabel': 'Ventes totales',
        'totalPurchasesLabel': 'Achats totaux',
        'cashInRegisterLabel': 'Espèces en caisse',
        'recentTransactionsLabel': 'Transactions récentes'
    },
    'ar': {
        'deleteStr': 'حذف',
        'createConsumables': 'إنشاء مستهلكات',
        'addFamilyMember': 'إضافة فرد للعائلة',
        'ledgerPayments': 'السجل / المدفوعات',
        'printDocument': 'طباعة المستند',
        'recordPayment': 'تسجيل الدفع',
        'viewPaymentsChecks': 'عرض المدفوعات والشيكات',
        'productNameLabel': 'اسم المنتج',
        'referenceLabel': 'المرجع (اختياري)',
        'purchasePriceLabel': 'سعر الشراء',
        'sellingPriceLabel': 'سعر البيع',
        'tier2PriceLabel': 'سعر الفئة 2 (اختياري)',
        'tier3PriceLabel': 'سعر الفئة 3 (اختياري)',
        'packagingLabel': 'التعبئة والتغليف',
        'unitTypeLabel': 'نوع الوحدة',
        'unitSizeLabel': 'حجم الوحدة',
        'unitsPerBoxLabel': 'الوحدات لكل صندوق',
        'baseMinStockLabel': 'الحد الأدنى في المستودع الأساسي',
        'magazinMinStockLabel': 'الحد الأدنى في المخزن',
        'arabicTagLabel': 'الوسم بالعربية',
        'frenchTagLabel': 'الوسم بالفرنسية',
        'spanishTagLabel': 'الوسم بالإسبانية',
        'saveStr': 'حفظ',
        'cancelStr': 'إلغاء',
        'stockLevelLabel': 'مستويات المخزون',
        'baseLabel': 'المستودع',
        'magazinLabel': 'المخزن',
        'dashboardTitle': 'لوحة القيادة',
        'stockTitle': 'المخزون',
        'salesTitle': 'المبيعات',
        'totalSalesLabel': 'إجمالي المبيعات',
        'totalPurchasesLabel': 'إجمالي المشتريات',
        'cashInRegisterLabel': 'النقد في الصندوق',
        'recentTransactionsLabel': 'العمليات الأخيرة'
    },
    'es': {
        'deleteStr': 'Eliminar',
        'createConsumables': 'Crear consumibles',
        'addFamilyMember': 'Añadir miembro familiar',
        'ledgerPayments': 'Libro mayor / Pagos',
        'printDocument': 'Imprimir documento',
        'recordPayment': 'Registrar pago',
        'viewPaymentsChecks': 'Ver pagos y cheques',
        'productNameLabel': 'Nombre del producto',
        'referenceLabel': 'Referencia (opcional)',
        'purchasePriceLabel': 'Precio de compra',
        'sellingPriceLabel': 'Precio de venta',
        'tier2PriceLabel': 'Precio Nivel 2 (opcional)',
        'tier3PriceLabel': 'Precio Nivel 3 (opcional)',
        'packagingLabel': 'Embalaje',
        'unitTypeLabel': 'Tipo de unidad',
        'unitSizeLabel': 'Tamaño de unidad',
        'unitsPerBoxLabel': 'Unidades por caja',
        'baseMinStockLabel': 'Stock mínimo base',
        'magazinMinStockLabel': 'Stock mínimo almacén',
        'arabicTagLabel': 'Etiqueta en árabe',
        'frenchTagLabel': 'Etiqueta en francés',
        'spanishTagLabel': 'Etiqueta en español',
        'saveStr': 'Guardar',
        'cancelStr': 'Cancelar',
        'stockLevelLabel': 'Niveles de stock',
        'baseLabel': 'Base',
        'magazinLabel': 'Magazín',
        'dashboardTitle': 'Tablero',
        'stockTitle': 'Inventario',
        'salesTitle': 'Ventas',
        'totalSalesLabel': 'Ventas totales',
        'totalPurchasesLabel': 'Compras totales',
        'cashInRegisterLabel': 'Efectivo en caja',
        'recentTransactionsLabel': 'Transacciones recientes'
    }
}

for lang, filepath in files.items():
    with open(filepath, 'r') as f:
        content = json.load(f)
        
    for k, v in data[lang].items():
        if k not in content:
            content[k] = v
        
    with open(filepath, 'w') as f:
        json.dump(content, f, indent=2, ensure_ascii=False)
        
print("ARBs updated.")
