import 'dart:convert';
import 'dart:io';

void main() {
  final files = {
    'en': 'lib/src/localization/arb/app_en.arb',
    'fr': 'lib/src/localization/arb/app_fr.arb',
    'ar': 'lib/src/localization/arb/app_ar.arb',
    'es': 'lib/src/localization/arb/app_es.arb',
  };

  final newKeys = {
    'en': {
      'clientsManagement': 'Clients Management',
      'searchClients': 'Search Clients',
      'selectAll': 'Select All',
      'noClientsFound': 'No clients found.',
      'noContactInfo': 'No contact info',
      'adminAccessRequired': 'Admin access required to delete.',
      'suppliersManagement': 'Suppliers Management',
      'searchSuppliers': 'Search Suppliers',
      'noSuppliersFound': 'No suppliers found.',
      'stockTransfer': 'Stock Transfer',
      'selectProductAndLocations': 'Please select product and locations',
      'sourceDestinationSame': 'Source and destination cannot be the same',
      'transferSuccessful': 'Transfer successful',
      'transferFailed': 'Transfer failed: ',
      'sourceLocation': 'Source Location',
      'destinationLocation': 'Destination Location',
      'mustBeGreaterThanZero': 'Must be greater than 0',
      'invalidNumber': 'Invalid number',
      'transferBtn': 'Transfer',
      'addBtn': 'Add',
      'nameOverridePdf': 'Name (Overrides Client Name in PDF)',
      'paymentRecordedSuccessfully': 'Payment recorded successfully!',
      'totalLabel': 'Total: ',
      'paidLabel': 'Paid: ',
      'remainingLabel': 'Remaining: ',
      'paymentAmount': 'Payment Amount',
      'setToFullRemaining': 'Set to full remaining',
      'paymentMethod': 'Payment Method',
      'recordBtn': 'Record',
      'paymentsRecord': 'Payments Record',
      'noPaymentsRecorded': 'No payments recorded.',
      'viewCheckImage': 'View Check Image',
      'close': 'Close',
      'deletePayment': 'Delete Payment',
      'deletePaymentConfirm': 'Delete Payment?',
      'deletePaymentDesc': 'This will algebraically reverse the payment.',
      'deletedStr': 'DELETED'
    },
    'fr': {
      'clientsManagement': 'Gestion des clients',
      'searchClients': 'Rechercher des clients',
      'selectAll': 'Tout sélectionner',
      'noClientsFound': 'Aucun client trouvé.',
      'noContactInfo': 'Pas d\'informations de contact',
      'adminAccessRequired': 'Accès administrateur requis pour supprimer.',
      'suppliersManagement': 'Gestion des fournisseurs',
      'searchSuppliers': 'Rechercher des fournisseurs',
      'noSuppliersFound': 'Aucun fournisseur trouvé.',
      'stockTransfer': 'Transfert de stock',
      'selectProductAndLocations': 'Veuillez sélectionner le produit et les emplacements',
      'sourceDestinationSame': 'La source et la destination ne peuvent pas être les mêmes',
      'transferSuccessful': 'Transfert réussi',
      'transferFailed': 'Échec du transfert : ',
      'sourceLocation': 'Emplacement source',
      'destinationLocation': 'Emplacement de destination',
      'mustBeGreaterThanZero': 'Doit être supérieur à 0',
      'invalidNumber': 'Nombre invalide',
      'transferBtn': 'Transférer',
      'addBtn': 'Ajouter',
      'nameOverridePdf': 'Nom (Remplace le nom du client dans le PDF)',
      'paymentRecordedSuccessfully': 'Paiement enregistré avec succès !',
      'totalLabel': 'Total : ',
      'paidLabel': 'Payé : ',
      'remainingLabel': 'Restant : ',
      'paymentAmount': 'Montant du paiement',
      'setToFullRemaining': 'Définir sur le reste total',
      'paymentMethod': 'Mode de paiement',
      'recordBtn': 'Enregistrer',
      'paymentsRecord': 'Enregistrement des paiements',
      'noPaymentsRecorded': 'Aucun paiement enregistré.',
      'viewCheckImage': 'Voir l\'image du chèque',
      'close': 'Fermer',
      'deletePayment': 'Supprimer le paiement',
      'deletePaymentConfirm': 'Supprimer le paiement ?',
      'deletePaymentDesc': 'Cela annulera algébriquement le paiement.',
      'deletedStr': 'SUPPRIMÉ'
    },
    'ar': {
      'clientsManagement': 'إدارة العملاء',
      'searchClients': 'البحث عن العملاء',
      'selectAll': 'تحديد الكل',
      'noClientsFound': 'لم يتم العثور على عملاء.',
      'noContactInfo': 'لا توجد معلومات اتصال',
      'adminAccessRequired': 'مطلوب وصول المسؤول للحذف.',
      'suppliersManagement': 'إدارة الموردين',
      'searchSuppliers': 'البحث عن موردين',
      'noSuppliersFound': 'لم يتم العثور على موردين.',
      'stockTransfer': 'نقل المخزون',
      'selectProductAndLocations': 'يرجى تحديد المنتج والمواقع',
      'sourceDestinationSame': 'لا يمكن أن يكون المصدر والوجهة متطابقين',
      'transferSuccessful': 'تم النقل بنجاح',
      'transferFailed': 'فشل النقل: ',
      'sourceLocation': 'موقع المصدر',
      'destinationLocation': 'موقع الوجهة',
      'mustBeGreaterThanZero': 'يجب أن يكون أكبر من 0',
      'invalidNumber': 'رقم غير صالح',
      'transferBtn': 'نقل',
      'addBtn': 'إضافة',
      'nameOverridePdf': 'الاسم (يتجاوز اسم العميل في ملف PDF)',
      'paymentRecordedSuccessfully': 'تم تسجيل الدفع بنجاح!',
      'totalLabel': 'الإجمالي: ',
      'paidLabel': 'المدفوع: ',
      'remainingLabel': 'المتبقي: ',
      'paymentAmount': 'مبلغ الدفع',
      'setToFullRemaining': 'تعيين إلى كامل المتبقي',
      'paymentMethod': 'طريقة الدفع',
      'recordBtn': 'تسجيل',
      'paymentsRecord': 'سجل المدفوعات',
      'noPaymentsRecorded': 'لم يتم تسجيل أي مدفوعات.',
      'viewCheckImage': 'عرض صورة الشيك',
      'close': 'إغلاق',
      'deletePayment': 'حذف الدفع',
      'deletePaymentConfirm': 'هل تريد حذف الدفع؟',
      'deletePaymentDesc': 'سيؤدي هذا إلى عكس الدفع جبريًا.',
      'deletedStr': 'محذوف'
    },
    'es': {
      'clientsManagement': 'Gestión de clientes',
      'searchClients': 'Buscar clientes',
      'selectAll': 'Seleccionar todo',
      'noClientsFound': 'No se encontraron clientes.',
      'noContactInfo': 'Sin información de contacto',
      'adminAccessRequired': 'Se requiere acceso de administrador para eliminar.',
      'suppliersManagement': 'Gestión de proveedores',
      'searchSuppliers': 'Buscar proveedores',
      'noSuppliersFound': 'No se encontraron proveedores.',
      'stockTransfer': 'Transferencia de stock',
      'selectProductAndLocations': 'Seleccione el producto y las ubicaciones',
      'sourceDestinationSame': 'El origen y el destino no pueden ser los mismos',
      'transferSuccessful': 'Transferencia exitosa',
      'transferFailed': 'Fallo en la transferencia: ',
      'sourceLocation': 'Ubicación de origen',
      'destinationLocation': 'Ubicación de destino',
      'mustBeGreaterThanZero': 'Debe ser mayor que 0',
      'invalidNumber': 'Número inválido',
      'transferBtn': 'Transferir',
      'addBtn': 'Añadir',
      'nameOverridePdf': 'Nombre (Anula el nombre del cliente en el PDF)',
      'paymentRecordedSuccessfully': '¡Pago registrado con éxito!',
      'totalLabel': 'Total: ',
      'paidLabel': 'Pagado: ',
      'remainingLabel': 'Restante: ',
      'paymentAmount': 'Monto del pago',
      'setToFullRemaining': 'Establecer al total restante',
      'paymentMethod': 'Método de pago',
      'recordBtn': 'Registrar',
      'paymentsRecord': 'Registro de pagos',
      'noPaymentsRecorded': 'No hay pagos registrados.',
      'viewCheckImage': 'Ver imagen del cheque',
      'close': 'Cerrar',
      'deletePayment': 'Eliminar pago',
      'deletePaymentConfirm': '¿Eliminar pago?',
      'deletePaymentDesc': 'Esto revertirá algebraicamente el pago.',
      'deletedStr': 'ELIMINADO'
    }
  };

  for (final entry in files.entries) {
    final lang = entry.key;
    final path = entry.value;
    final file = File(path);
    if (file.existsSync()) {
      final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      json.addAll(newKeys[lang]!);
      
      const encoder = JsonEncoder.withIndent('  ');
      file.writeAsStringSync(encoder.convert(json) + '\n');
      print('Updated \$lang');
    }
  }
}
